// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingStore.ProductAPI.Data;

#nullable disable

namespace ShoppingStore.ProductAPI.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20240830011606_CategoryColumnAdded")]
    partial class CategoryColumnAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ShoppingStore.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "",
                            Description = "Esto es un cuaderno",
                            Name = "Cuaderno",
                            Price = 50.990000000000002
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "",
                            Description = "Esto es una computadora",
                            Name = "Computadora",
                            Price = 20000.990000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
